# Schema registry service
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.6
    hostname: schema-registry
    container_name: schema_registry_container
    ports:
      - '8998:8081'
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://167.172.78.79:9092,PLAINTEXT://167.172.78.79:9093,PLAINTEXT://167.172.78.79:9094
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_GROUP_ID: schema-registry-cluster
      SCHEMA_REGISTRY_MASTER_ELIGIBLITY: "true"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    volumes:
      - schema-registry-data:/var/lib/schema-registry/data