version: '3.9'

services:
  notification-service:
    container_name: notification-service
    build:
      context: . # Use the current directory for building
    ports:
      - "8888:8888" # Map the application port
    #    environment:
    #      SPRING_PROFILES_ACTIVE: prod # Set Spring profile if needed
    volumes:
      - logs:/app/logs # Optional: Map logs to a local directory

volumes:
  logs: